# -*- coding: utf-8 -*-
"""task-12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KyRpSP4AIQAuHJ1nRvi4-Jbjuv74eMCB
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv("Titanic-Dataset.csv")

df.head()

df.shape

missing_values = df.isnull().sum()

print(missing_values)

missing_summary = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Total Values": len(df),
    "Missing Percentage": (df.isnull().sum() / len(df)) * 100
})

print(missing_summary)

missing_summary[missing_summary["Missing Values"] > 0]

total_missing = df.isnull().sum().sum()

print("Total missing values:", total_missing)

print("Has missing values:", df.isnull().values.any())